title: (think outside the cube?)
description: A webapp visualizer that compares psychedelics / altered states of consciousness to spatial dimensions.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
github:
  is_project_page: false
