title: (think outside the cube?)
description: A webapp visualizer that compares psychedelics / altered states of consciousness to spatial dimensions.
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
